# Generated by Django 3.1 on 2020-09-08 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('khmarads', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khmarads.ad')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ad', 'owner')},
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='favourites',
            field=models.ManyToManyField(related_name='favourite_ads', through='khmarads.Fav', to=settings.AUTH_USER_MODEL),
        ),
    ]
